### ISSUE TITLE
Fix compatibility with ESPHome 2022.5.0

### ISSUE THREAD

**Issue by gorbunovav** [Lyr3x/Roode#125]
**Describe the bug**
With the ESPHome 2022.5.0 release the `set` method of the `Number` component was removed.

The proper way to set the value is to use the `make_call` method:
https://esphome.io/components/number/index.html?highlight=make_call

**To Reproduce**
Update to ESPHome 2022.5.0 and try to compile the firmware.

**Expected behavior**
Compilation completes succesfully.

**Comment by Lyr3x** [comment]
Thanks. Yes unfortunately they removed that function. I saw that you are working on a PR? Happy to merge if you are ready.

**Comment by gorbunovav** [comment]
@Lyr3x Hi! Yes, the PR is ready to be merged.

**Comment by Lyr3x** [comment]
Thank you very much for the contribution

**Comment by Lyr3x** [comment]
Can you open the PR to upstream please? 🙏
