### ISSUE TITLE
The sensor is seriously affected by light in daytime

### ISSUE THREAD

**Issue by roc634** [Lyr3x/Roode#129]
**Describe the bug**
The sensor seems to be seriously affected by light in daytime. I install the sensor in the door frame and use it to control the light in my kitchen. It works like a charm at night. However, it's annoying in daytime, especially in the morning. The light is always on. It'll turn on soon even though I turn if off manually . 
Below is my floor plan. My living room is facing east. The sunlight will reach my living room is the morning. The area in front of the ketchen door is brighter when the sunlight comes in, but it's still 2-3 meters away from the kitchen door. 
<img width="500" alt="6cd451af5ed801670d9944d95e8f3274" src="https://user-images.githubusercontent.com/49619054/186495134-d9bac998-e899-474b-af3f-639921d7a8df.png">
It's seriously affected by the sunlight while works fine during other parts of the day. 
<img width="283" alt="2022-6-10 10-35-7" src="https://user-images.githubusercontent.com/49619054/186496051-c3f921ca-d1aa-4cfd-a022-60fa4a62d8a5.png">
<img width="279" alt="2022-7-9 0-7-28" src="https://user-images.githubusercontent.com/49619054/186496168-3eb93ad7-11d2-4e14-a5a2-49642cbfda6d.png">
<img width="258" alt="2022-8-7 1-15-44" src="https://user-images.githubusercontent.com/49619054/186496223-2dbdc35e-53ef-46b6-b54a-98e95ec221bb.png">
As you can see, the distance measured after sunrise is a mess.
<img width="777" alt="2022-8-12 0-58-14" src="https://user-images.githubusercontent.com/49619054/186496413-5e96f45c-13e0-46ea-baa4-7e44dbb1070e.png">
I've been trying different ways to solve this. I tilted the sensor. I've also changed several different power adapter but the situation is the same. I'm not sure if it's the problem of this individual sensor. Your help will be greatly appreciated. Thanks!

**Additional context**
By the way, have you tried the AMG8833 IR Thermal Camera? It is an 8x8 array of IR thermal sensors which is probably suitable for people counting, althought it's more expensive.

**Comment by Lyr3x** [comment]
That is a known limitation of the sensor. There is nothing we can do about it. There are multiple issues about that already. 
I suggest you look into mmWave sensors instead if you face light reflection issues

**Comment by roc634** [comment]
> That is a known limitation of the sensor. There is nothing we can do about it. There are multiple issues about that already. I suggest you look into mmWave sensors instead if you face light reflection issues

I'm also using APDS-9960 RGB and Gesture Sensor as people counter, it seems reliable, but it's detecting range is less than 20cm. It will be perfect if its detecting range is the same as GY-53.
I'm not that optimistic about mmWave sensors since they're detecting all moving objects rather than just human being.

**Comment by Lyr3x** [comment]
This is true. A combination of sensors is key here. I currently use heavily motion sensor + light sensor + mmWave sensor with a perfect result.

**Comment by artur90226** [comment]
> This is true. A combination of sensors is key here. I currently use heavily motion sensor + light sensor + mmWave sensor with a perfect result.

Which motion sensor are you using?
