### ISSUE TITLE
Random disconnects while Wifi connection stays active

### ISSUE THREAD

**Issue by EuleMitKeule** [Lyr3x/Roode#130]
**Describe the bug**
All of my ESPs randomly disconnect every few days. They are still connected to my router's Wifi, but are unreachable either by their IP or their .local domain. A power cycle fixes this problem.

**To Reproduce**
Let the sensors run for some days and see the disconnected state in ESPHome.

**Expected behavior**
The sensors should stay connected over long periods of time.

**Screenshots**

**Additional context**
[configuration.txt](https://github.com/Lyr3x/Roode/files/9472570/configuration.txt)

**Comment by Lyr3x** [comment]
That can happen for various reasons. Do you already have a indication on what's happening ?

**Comment by EuleMitKeule** [comment]
I believe this was caused by a bad solder connection.
