### ISSUE TITLE
FYI: made an esphome version of this

### ISSUE THREAD

**Issue by diplix** [Lyr3x/Roode#19]
@Lyr3x based on your work i managed to convert this (the 1.0 version) into a working [esphome](https://esphome.io) configuration: https://github.com/diplix/esphome-configuration

i’m using two of these and they’ve been working quite reliably for a couple oof weeks now. one esp8266 tof-sensor is combined with a door sensor, the other one also reuses measured values for some kind oof lichtschranke to act before a count is registered. OTA updates are working  (thanks to esphome) and on the fly calibartion should be doable as well.

**Comment by Lyr3x** [comment]
Awesome work! Due to my master Thesis I have no time at all at the moment... I would love too see and check your work! 

Are you interested in open a PR which includes the esphome stuff?

**Comment by diplix** [comment]
iff you want to test my configuration you could (after installing esphome and checking/configuring the platform in `tof_sensor.yaml`) just run `esphome tof_sensor.yaml compile` to see if it compiles and `esphome tof_sensor.yaml run` to compile and upload on a esp8266 or esp32.
