### ISSUE TITLE
Random disconnects of the ESPHome API

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Roode#27]
**Describe the bug**
When controlling Roode from HA it come sometimes to an disconnect after a command is sent

**To Reproduce**
Sent recalibrate command

**Expected behavior**
Recalibration occurs, but after the recalibration started the esp disconnects for a few seconds

**Comment by Lyr3x** [comment]
We can't enable both mqtt and the native api without stability issues. We need MQTT to receive commands and react on them in the code. Currently the native api is not capable of that. However, it seems that they develop that possibility.

**Comment by Lyr3x** [comment]
Cleaning up exposed sensors + setting a higher Timeout mitigated the issue well

**Comment by noxhirsch** [comment]
> We can't enable both mqtt and the native api without stability issues. We need MQTT to receive commands and react on them in the code. Currently the native api is not capable of that. However, it seems that they develop that possibility.

@Lyr3x Sorry to respond to a closed issue here, but shouldn't this be possible with user-defined services so that MQTT isn't needed anymore?
https://esphome.io/components/api.html#user-defined-services

I use these user-defined services to trigger specific commands or send position data to my blinds:
![image](https://user-images.githubusercontent.com/30938717/133322441-03975f44-4feb-4c7a-a27e-7fc23f3a5dbe.png)

**Comment by Lyr3x** [comment]
Thank you very much! I didn't know about that. I'll reopen the issue and will test that to ditch MQTT completely.

**Comment by Lyr3x** [comment]
Do you know if it's possible to use just a lambda in the `then` part?

**Comment by Lyr3x** [comment]
Do you know if it's possible to use just a lambda in the `then` part?

**Comment by noxhirsch** [comment]
If that's what you mean, then yes, it's possible:

```
    - service: slow_position
      variables:
        pos: float
      then:
        - [...]
        - lambda: 'id(tilt).update();'
        - [...]
```
(this is snippet of my blinds-script)

**Comment by Lyr3x** [comment]
Awesome! Thanks again

**Comment by Lyr3x** [comment]
With #43 I removed MQTT and switched to NativeAPI all the way. Services are registered in the example configurations to achieve resetting, counter setting and recalibration.
