### ISSUE TITLE
Entry and exit event sensors

### ISSUE THREAD

**Issue by DutchDeffy** [Lyr3x/Roode#29]
**Describe the solution you'd like**
As the title implies. Maybe you can make an additional sensor entity that tells whether someone enters or leaves. So the actual count of people can be handled on a centralised home assistant entity of the counter domain. (counter.**) Also, with this method multiple sensors can be used in a room with, for example, more entrances. 

**Additional context**
Keep up the good work!

**Comment by Lyr3x** [comment]
Part of #43
