### ISSUE TITLE
Provide Recalibration as button

### ISSUE THREAD

**Issue by Lyr3x** [Lyr3x/Roode#66]
As of 2021.12 ESPHome and HA support button entities which do a certain action on press. That is something that were missing to implement a proper recalibration, our counter reset button.

**Comment by Lyr3x** [comment]
```
- platform: template
    name: $friendly_name Recalibrate
    on_press:
      - lambda: id(roode_platform)->recalibration();
```

This is working for now but it should be a `-platform: roode` button

**Comment by sunshine-hass** [comment]
Hello, have you actually tested this project?
I tested https://github.com/Andrea-Fox/peopleCounter before, and it can meet my needs. Now the home is being renovated and I need to integrate the ESPhome version.

**Comment by Lyr3x** [comment]
I don't get your question. Andreas Version is a very basic Version and not really comparable anymore.
